FetchApplicationByPrid:
   Prereg_FetchApplicationByPrid_All_Valid_Smoke_sid:
      endPoint: /preregistration/v1/applications/prereg/{preRegistrationId}
      role: batch
      restMethod: get
      inputTemplate: preReg/FetchApplicationByPrid/fetchApplicationByPrid
      outputTemplate: preReg/FetchApplicationByPrid/fetchApplicationByPridResult
      input: '{
  "preRegistrationId": "$ID:CreatePrereg_All_Valid_Smoke_sid_preRegistrationId$"
}'
      output: '{
  "preRegistrationId": "59286406501581"
}'
   Prereg_FetchApplicationByPrid_inValid_preRegistrationId_sid:
      endPoint: /preregistration/v1/applications/prereg/{preRegistrationId}
      role: batch
      restMethod: get
      inputTemplate: preReg/FetchApplicationByPrid/fetchApplicationByPrid
      outputTemplate: preReg/error
      input: '{
  "preRegistrationId": "ggfr3567ugg"
}'
      output: '{
   "errors": [
    {
      "errorCode": "PRG_BOOK_RCI_013",
      "message": "Booking data not found"
    }
  ]
}'