GetConfigs:
   sync_GetConfigs_smoke:
      endPoint: /v1/syncdata/configs
      role: admin
      restMethod: get
      inputTemplate: syndata/GetConfigs/getConfigs
      outputTemplate: syncdata/GetConfigs/getConfigsResult
      input: '{
      }'
      output: '{
          "response": {
              
          }
      }'