GetInputAttributeValues:
   Resident_GetInputAttributeValues1_UIN_all_Valid_Smoke:
      endPoint: /resident/v1/identity/info/type/{schemaType}
      role: residentNew
      restMethod: get
      inputTemplate: resident/GetInputAttributeValues/getInputAttributeValues
      outputTemplate: resident/GetInputAttributeValues/getInputAttributeValuesResult
      input: '{
      	"schemaType":"update-demographics"
}'
      output: '{
}'

   Resident_GetInputAttributeValues2_UIN_all_Valid_Smoke:
      endPoint: /resident/v1/identity/info/type/{schemaType}
      role: residentNew
      restMethod: get
      inputTemplate: resident/GetInputAttributeValues/getInputAttributeValues
      outputTemplate: resident/GetInputAttributeValues/getInputAttributeValuesResult
      input: '{
      	"schemaType":"share-credential"
}'
      output: '{
}'

   Resident_GetInputAttributeValues3_UIN_all_Valid_Smoke:
      endPoint: /resident/v1/identity/info/type/{schemaType}
      role: residentNew
      restMethod: get
      inputTemplate: resident/GetInputAttributeValues/getInputAttributeValues
      outputTemplate: resident/GetInputAttributeValues/getInputAttributeValuesResult
      input: '{
      	"schemaType":"personalized-card"
}'
      output: '{
}'